# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8c4289898dc9a3e436f612bf681f5e6f19fa3a1f759ee997e2afe8ab766238bd5a48a2b6de157f4f98da8005c8a60914927f8cf027e9d9e1651b2488f8febe5

test:
  secret_key_base: 2249ce23dfe6dd847075a9e0b9d4b9eca0f7d48595300c8269645a22730434a57ada17197475c6ad743f97d409198925fce04c10ef03e9ec5f928883faa60aac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
